'use client' // Indica que este componente se ejecuta del lado del cliente (en el navegador).

//import type { Metadata } from "next";

// Importamos la función `localFont` de Next.js para cargar fuentes locales.
import localFont from "next/font/local";

import "./globals.css";

// Importamos las herramientas necesarias de `react-query` para manejar consultas.
import { QueryClient, QueryClientProvider } from 'react-query';

// Cargamos la fuente "Geist Sans" desde un archivo local y definimos su variable CSS.
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

// Cargamos la fuente "Geist Mono" desde un archivo local y definimos su variable CSS.
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//export const metadata: Metadata = {
//title: "Create Next App",
//description: "Generated by create next app",
//}; 

// Función principal que define el layout raíz de la aplicación.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Creamos una nueva instancia de QueryClient para manejar las consultas.
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}> {/* Proveedor para el cliente de consultas. */}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </QueryClientProvider>
    </html>
  );
}
